import { ShortText, Url, WithUniqueId } from "../types/generics";

/**
 * CRUD Consumer Pattern
 *
 * @remarks
 * This interface defines a **contract** for all services responsible
 * for Create / Read / Update / Delete operations against a remote API.
 *
 * Design principles:
 * - The consumer **does not expose transport details** (HTTP, RxJS, etc.)
 * - All operations return **normalized responses**
 * - Business-level failures are represented in the response, not via exceptions
 *
 * Typical usage:
 * - Application services
 * - Infrastructure adapters (REST, GraphQL, gRPC, etc.)
 *
 * @typeParam Entity - Entity type handled by the service.
 * Must expose a unique identifier.
 */
export interface CrudConsumer<Entity extends WithUniqueId> {

  /**
   * Base API endpoint used by this consumer.
   *
   * @remarks
   * - Represents the root URL for the resource
   * - Concrete implementations decide how it is used internally
   *
   * @example
   * `http://endpoint/api/users`
   */
  endpoint: Url;

  /**
   * Creates a new entity.
   *
   * @param data - Entity payload without its identifier
   *
   * @remarks
   * - The identifier is expected to be generated by the backend
   * - The operation result is always returned as a normalized response
   */
  create(
    data: Omit<Entity, 'id'>
  ): Promise<CrudConsumerResponse<Entity>>;

  /**
   * Reads all entities.
   *
   * @remarks
   * - Returns a collection of entities
   * - Failures are reported through the response status
   */
  read(): Promise<CrudConsumerResponse<Entity[]>>;

  /**
   * Reads a single entity by its identifier.
   *
   * @param target - Unique identifier of the entity to read
   *
   * @remarks
   * - Supports falsy identifiers such as `0` or empty strings
   */
  read(
    target: Entity['id']
  ): Promise<CrudConsumerResponse<Entity>>;

  /**
   * Updates an existing entity.
   *
   * @param target - Entity being updated (identifier is taken from it)
   * @param data - Partial payload excluding the identifier
   *
   * @remarks
   * - The update strategy (PUT vs PATCH) is an implementation detail
   * - Only the provided fields are expected to change
   */
  update(
    target: Entity,
    data: Partial<Omit<Entity, 'id'>>
  ): Promise<CrudConsumerResponse<Entity>>;

  /**
   * Deletes an entity.
   *
   * @param target - Entity to be deleted
   *
   * @remarks
   * - Implementations may return the deleted entity or null payload
   *   depending on backend behavior (e.g. HTTP 204)
   */
  delete(
    target: Entity
  ): Promise<CrudConsumerResponse<Entity>>;
}

/**
 * Stable, machine-oriented codes describing CRUD operation outcomes.
 *
 * @remarks
 * - Codes are intended for logging, analytics, UI mapping and i18n
 * - They MUST remain stable over time
 * - Human-readable wording is intentionally decoupled from these codes
 */
export type CrudResponseCode =
  | "CRUD.CREATE.SUCCESS"
  | "CRUD.CREATE.ERROR"
  | "CRUD.READ.SUCCESS"
  | "CRUD.READ.ERROR"
  | "CRUD.READ_ALL.SUCCESS"
  | "CRUD.READ_ALL.ERROR"
  | "CRUD.UPDATE.SUCCESS"
  | "CRUD.UPDATE.ERROR"
  | "CRUD.DELETE.SUCCESS"
  | "CRUD.DELETE.ERROR";

/**
 * Normalized response returned by all CRUD consumers.
 *
 * @typeParam P - Payload type returned by the operation
 *
 * @remarks
 * Design goals:
 * - Provide a **single, predictable response shape**
 * - Avoid throwing exceptions for business-level errors
 * - Allow easy branching in UI and application layers
 *
 * Typical usage:
 * ```ts
 * const res = await service.create(data);
 * if (res.status === 'success') {
 *   // use res.payload
 * } else {
 *   // display res.message or map res.code
 * }
 * ```
 */
export interface CrudConsumerResponse<P> {

  /**
   * High-level outcome of the operation.
   */
  status: 'success' | 'error';

  /**
   * Stable code describing the operation result.
   *
   * @remarks
   * Intended for machines, not end users.
   */
  code: CrudResponseCode;

  /**
   * Short, human-readable message describing the outcome.
   *
   * @remarks
   * - Intended for UI display or logs
   * - Length and content are constrained by `ShortText`
   */
  message: ShortText;

  /**
   * Payload returned by the operation.
   *
   * @remarks
   * - Present only when `status === 'success'`
   * - Explicitly null on failure
   */
  payload: P | null;
}
